const output = `---STATION THIRTEEN LIFE SUPPORT CYCLING PROCEDURES---\n
  DANGER: INITIATING THIS PROCEDURE AT ANY TIME\n
  WHEN CYCLING IS NOT REQUIRED WILL RESULT IN LIFE SUPPORT FAILURE\n
  AND IMMEDIATE PERSONNEL DEATH.\n
  THIS IS GENERALLY NOT ADVISABLE.
  \n
  TO ENGAGE LIFE SUPPORT CYCLING:
  \n
  DANGER: HIGH DEGREE OF SYNCHRONIZATION REQUIRED
  \n PLANNING ADVISED BEFORE INITIATING PROCEDURE.\n
  ----------------------------------\n
  STATION CREW IN LIFE SUPPORT\n
  STATION CREW IN COMMAND CENTER\n
  STATION CREW IN CARGO BAY\n
  STATION CREW IN TECH LAB\n
  \n CREW MUST BE READY TO ROTATE
  LIFE SUPPORT CREW ACTIVATE LIFE SUPPORT CYCLING\n
  WITHIN 5 SECONDS, CARGO BAY CREW ACTIVATE VENTILATION SYSTEM A\n
  WITHIN 5 SECONDS, TECH LAB CREW ACTIVATE ELECTROLYSIS\n
  WITHIN 5 SECONDS, COMMAND CENTER CREW ACTIVATE PRESSURE EQUALIZER\n
  WITHIN 5 SECONDS, REACTOR CREW ACTIVATE APU
  WITHIN 5 SECONDS, ENGINEERING BAY CREW ACTIVATE FILTRATION SYSTEM \n
  WITHIN 5 SECONDS, CARGO BAY CREW ACTIVATE VENTILATION SYSTEM B\n
  WITHIN 5 SECONDS, CYBERNETICS CORE CREW ACTIVATE \nMAINFRAME RESYNCHRONIZATION\n
  WITHIN 5 SECONDS, ENGINEERING BAY CREW ACTIVATE PURIFICATION SYSTEM \n
  WITHIN 5 SECONDS, COMMAND CENTER CREW ACTIVATE SECURITY OVERRIDE\n
  WITHIN 5 SECONDS, TECH LAB CREW ACTIVATE NITROGEN SATURATOR\n
  WITHIN 5 SECONDS, CARGO BAY CREW ACTIVATE VENTILATION SYSTEM C\n
  WITHIN 5 SECONDS, LIFE SUPPORT CREW ACTIVATE LIFE SUPPORT FAILSAFE \n
  `;

export { output };
