const output = `---STATION THIRTEEN MAINFRAME SHUTDOWN PROCEDURES---\n
  DANGER: INITIATING THIS PROCEDURE AT ANY TIME\n
  WHEN SHUTDOWN IS NOT REQUIRED WILL RESULT IN STATION\n
  MANAGEMENT FAILURE. UNAUTHORIZED PERSONNEL MUST NOT ENGAGE\n
  MAINFRAME SHUTDOWN PROCEDURES.
  \n
  TO ENGAGE MAINFRAME SHUTDOWN:
  \n
  ----------------------------------\n
  STATION CREW IN CYBERNETICS CORE\n
  \n
  USE TERMINALS IN CYBERNETICS CORE\n
  TO DECODE MAINFRAME RESET CODE\n 
  EACH TERMINAL CONTAINS ONE FRAGMENT OF MAINFRAME\n
  SEND RESET MESSAGE TO GAMEMASTER
  ERROR: CORRUPTED BLOCK AT 0xf
  
  REACTOR CREW ACTIVATE RESET SWITCH\n
  AND WAIT FOR ONE GREEN SIGNAL IN COMMAND CENTER\n
  CYBERNETICS CREW ACTIVATE RESET SWITCH\n
  AND WAIT FOR THREE GREEN SIGNALS IN CARGO BAY\n
  TECH LAB CREW ACTIVATE RESET SWITCH\n
  AND WAIT FOR ONE GREEN SIGNAL IN LIFE SUPPORT\n
  COMMAND CENTER CREW ACTIVATE RESET SWITCH\n
  MASTER REACTOR RESET COMPLETE
  `;

export { output };
