const output = `---STATION THIRTEEN MAINFRAME SHUTDOWN PROCEDURES---\n
  DANGER: INITIATING THIS PROCEDURE AT ANY TIME\n
  WHEN SHUTDOWN IS NOT REQUIRED WILL RESULT IN STATION\n
  MANAGEMENT FAILURE. UNAUTHORIZED PERSONNEL MUST NOT ENGAGE\n
  MAINFRAME SHUTDOWN PROCEDURES.
  \n
  TO ENGAGE MAINFRAME SHUTDOWN:
  \n
  ----------------------------------\n
  STATION CREW IN CYBERNETICS CORE\n
  \n
  USE TERMINALS IN CYBERNETICS CORE\n
  TO DECODE MAINFRAME RESET CODE\n 
  EACH TERMINAL CONTAINS ONE FRAGMENT OF RESET CODE\n
  \n USE FRAGMENT COMMAND TO GET MESSAGE
  SEND RESET MESSAGE TO GAMEMASTER\n
  \n
  SEND ALL FRAGMENTS CONCATENATED TOGETHER\n
  IN THIS FORMAT:\n
  RESET_MAINFRAME (COMPLETE CODE HERE WITHOUT PARENTHESES)\n
  \n MAINFRAME CODE IS AS FOLLOWS:
  ERROR: CANNOT FETCH MAINFRAME CODE:\n
  CORRUPTED BLOCK AT 0xf
  `;

export { output };
