const output = `---STATION THIRTEEN MASTER REACTOR RESET PROCEDURES---\n
  DANGER: INITIATING THIS PROCEDURE AT ANY TIME\n
  WHEN RESET IS NOT REQUIRED WILL RESULT IN STATION\n
  DESTRUCTION. UNAUTHORIZED PERSONNEL MUST NOT ENGAGE\n
  REACTOR RESET PROCEDURES.
  \n
  TO ENGAGE MASTER REACTOR RESET:
  \n
  ----------------------------------\n
  REACTOR CREW ACTIVATE REACTOR MAIN CYCLE SWITCH\n
  AFTER MAIN CYCLE SWITCH, \n
  WHILE THERE IS ONE GREEN SIGNAL IN COMMAND CENTER\n
  ACTIVATE SUBSTATION A RESET\n
  AFTER SUBSTATION A,\n
  WHILE THERE IS ONE GREEN SIGNAL IN ENGINEERING BAY\n
  AND ONE GREEN SIGNAL IN COMMAND CENTER\n
  ACTIVATE SUBSTATION B RESET\n
  AFTER SUBSTATION B,\n
  WHILE THERE ARE TWO GREEN SIGNALS IN COMMAND CENTER\n
  AND ONE RED SIGNAL IN MEDLAB\n
  ACTIVATE SUBSTATION C RESET\n
  AFTER SUBSTATION C,\n
  WHILE THERE ARE FOUR SIGNALS ARE LIT IN REACTOR\n
  SIMULTAENOUSLY, WITHIN THREE SECONDS\n
  PRESS ALL FOUR MASTER REACTOR RESET BUTTONS\n
  MASTER REACTOR RESET COMPLETE
  `;

export { output };
