const output = `---STATION THIRTEEN MASTER REACTOR RESET PROCEDURES---\n
  DANGER: INITIATING THIS PROCEDURE AT ANY TIME\n
  WHEN RESET IS NOT REQUIRED WILL RESULT IN STATION\n
  DESTRUCTION. UNAUTHORIZED PERSONNEL MUST NOT ENGAGE\n
  REACTOR RESET PROCEDURES.
  \n
  TO ENGAGE MASTER REACTOR RESET:
  \n
  ----------------------------------\n
  STATION CREW IN REACTOR\n
  STATION CREW IN CYBERNETICS CORE\n
  STATION CREW IN TECH LAB\n
  STATION CREW IN COMMAND CENTER\n
  REACTOR CREW ACTIVATE REACTOR MAIN CYCLE SWITCH\n
  WHILE THERE IS ONE GREEN SIGNAL IN COMMAND CENTER\n
  CYBERNETICS CORE CREW ACTIVATE SUBSTATION A RESET\n
  WHILE THERE IS ONE GREEN SIGNAL IN ENGINEERING BAY\n
  TECH LAB CREW ACTIVATE SUBSTATION B RESET\n
  WHILE ALL THREE SIGNALS ARE LIT IN COMMAND CENTER\n
  SIMULTAENOUSLY, WITHIN THREE SECONDS\n
  REACTOR CREW PRESS MASTER REACTOR RESET\n
  CARGO BAY CREW PRESS MASTER REACTOR RESET\n
  ENGINEERING BAY CREW PRESS MASTER REACTOR RESET\n 
  MASTER REACTOR RESET COMPLETE
  `;

export { output };
