const output = `---STATION THIRTEEN MASTER REACTOR RESET PROCEDURES---\n
  DANGER: INITIATING THIS PROCEDURE AT ANY TIME\n
  WHEN RESET IS NOT REQUIRED WILL RESULT IN STATION\n
  DESTRUCTION. UNAUTHORIZED PERSONNEL MUST NOT ENGAGE\n
  REACTOR RESET PROCEDURES.
  \n
  TO ENGAGE MASTER REACTOR RESET:
  \n
  ----------------------------------\n
  STATION CREW IN REACTOR\n
  STATION CREW IN CYBERNETICS CORE\n
  STATION CREW IN TECH LAB\n
  STATION CREW IN COMMAND CENTER\n
  REACTOR CREW ACTIVATE RESET SWITCH\n
  AND WAIT FOR ONE GREEN SIGNAL IN COMMAND CENTER\n
  CYBERNETICS CREW ACTIVATE RESET SWITCH\n
  AND WAIT FOR THREE GREEN SIGNALS IN CARGO BAY\n
  TECH LAB CREW ACTIVATE RESET SWITCH\n
  AND WAIT FOR ONE GREEN SIGNAL IN LIFE SUPPORT\n
  COMMAND CENTER CREW ACTIVATE RESET SWITCH\n
  MASTER REACTOR RESET COMPLETE
  `;

export { output };
